## PANDAS
Pandas is an open-source Python library used for data manipulation, analysis and cleaning. It provides fast and flexible tools to work with tabular data, similar to spreadsheets or SQL tables.
A fast and efficient DataFrame object for data manipulation with integrated indexing;

Tools for reading and writing data between in-memory data structures and different formats: CSV and text files, Microsoft Excel, SQL databases, and the fast HDF5 format;

Intelligent data alignment and integrated handling of missing data: gain automatic label-based alignment in computations and easily manipulate messy data into an orderly form;

Flexible reshaping and pivoting of data sets;

Intelligent label-based slicing, fancy indexing, and subsetting of large data sets;

Columns can be inserted and deleted from data structures for size mutability;

Aggregating or transforming data with a powerful group by engine allowing split-apply-combine operations on data sets;

High performance merging and joining of data sets;

Hierarchical axis indexing provides an intuitive way of working with high-dimensional data in a lower-dimensional data structure;

In [1]:
import pandas as pd

In [2]:
# Titanic Data set

df = pd.read_csv("https://raw.githubusercontent.com/datasciencedojo/datasets/master/titanic.csv")

In [3]:
df.head(10)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S
5,6,0,3,"Moran, Mr. James",male,NaN,0,0,330877,8.4583,NaN,Q
6,7,0,1,"McCarthy, Mr. Timothy J",male,54.0,0,0,17463,51.8625,E46,S
7,8,0,3,"Palsson, Master. Gosta Leonard",male,2.0,3,1,349909,21.0750,NaN,S
8,9,1,3,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,2,347742,11.1333,NaN,S
9,10,1,2,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,0,237736,30.0708,NaN,C

In [4]:
df.tail()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
886,887,0,2,"Montvila, Rev. Juozas",male,27.0,0,0,211536,13.00,NaN,S
887,888,1,1,"Graham, Miss. Margaret Edith",female,19.0,0,0,112053,30.00,B42,S
888,889,0,3,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1,2,W./C. 6607,23.45,NaN,S
889,890,1,1,"Behr, Mr. Karl Howell",male,26.0,0,0,111369,30.00,C148,C
890,891,0,3,"Dooley, Mr. Patrick",male,32.0,0,0,370376,7.75,NaN,Q

In [5]:
df.dtypes

PassengerId      int64
Survived         int64
Pclass           int64
Name            object
Sex             object
Age            float64
SibSp            int64
Parch            int64
Ticket          object
Fare           float64
Cabin           object
Embarked        object
dtype: object

In [6]:
# To perform basic analysis

df.describe()

,PassengerId,Survived,Pclass,Age,SibSp,Parch,Fare
count,891.000000,891.000000,891.000000,714.000000,891.000000,891.000000,891.000000
mean,446.000000,0.383838,2.308642,29.699118,0.523008,0.381594,32.204208
std,257.353842,0.486592,0.836071,14.526497,1.102743,0.806057,49.693429
min,1.000000,0.000000,1.000000,0.420000,0.000000,0.000000,0.000000
25%,223.500000,0.000000,2.000000,20.125000,0.000000,0.000000,7.910400
50%,446.000000,0.000000,3.000000,28.000000,0.000000,0.000000,14.454200
75%,668.500000,1.000000,3.000000,38.000000,1.000000,0.000000,31.000000
max,891.000000,1.000000,3.000000,80.000000,8.000000,6.000000,512.329200

In [7]:
# To take data of your own choice

df[['Name','Sex','Ticket','Fare','Sex','Age']]

,Name,Sex,Ticket,Fare,Sex,Age
0,"Braund, Mr. Owen Harris",male,A/5 21171,7.2500,male,22.0
1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,PC 17599,71.2833,female,38.0
2,"Heikkinen, Miss. Laina",female,STON/O2. 3101282,7.9250,female,26.0
3,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,113803,53.1000,female,35.0
4,"Allen, Mr. William Henry",male,373450,8.0500,male,35.0
...,...,...,...,...,...,...
886,"Montvila, Rev. Juozas",male,211536,13.0000,male,27.0
887,"Graham, Miss. Margaret Edith",female,112053,30.0000,female,19.0
888,"Johnston, Miss. Catherine Helen ""Carrie""",female,W./C. 6607,23.4500,female,NaN
889,"Behr, Mr. Karl Howell",male,111369,30.0000,male,26.0
890,"Dooley, Mr. Patrick",male,370376,7.7500,male,32.0

In [8]:
# To figure out how many rows or colomns have float data type(or anyother)

df[df.dtypes[df.dtypes=='float'].index]

      Age     Fare
0    22.0   7.2500
1    38.0  71.2833
2    26.0   7.9250
3    35.0  53.1000
4    35.0   8.0500
..    ...      ...
886  27.0  13.0000
887  19.0  30.0000
888   NaN  23.4500
889  26.0  30.0000
890  32.0   7.7500

[891 rows x 2 columns]

In [9]:
df[df.dtypes[df.dtypes=='int'].index]

     PassengerId  Survived  Pclass  SibSp  Parch
0              1         0       3      1      0
1              2         1       1      1      0
2              3         1       3      0      0
3              4         1       1      1      0
4              5         0       3      0      0
..           ...       ...     ...    ...    ...
886          887         0       2      0      0
887          888         1       1      0      0
888          889         0       3      1      2
889          890         1       1      0      0
890          891         0       3      0      0

[891 rows x 5 columns]

In [10]:
df.columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [11]:
# To slice any column or row of your own choice
df[['Ticket']][5:15]

       Ticket
5      330877
6       17463
7      349909
8      347742
9      237736
10    PP 9549
11     113783
12  A/5. 2151
13     347082
14     350406

In [12]:
# Need jump or alternate
df[['Ticket']][5:15:3]

    Ticket
5   330877
8   347742
11  113783
14  350406

In [13]:
# Slice with more then 2 columns
df[['Ticket', 'Age']][5:15:3]

    Ticket   Age
5   330877   NaN
8   347742  27.0
11  113783  58.0
14  350406  14.0

In [14]:
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [15]:
# Add custom column at the end

df['Bilal'] = 3
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Bilal
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3

In [16]:
# Add custom column at any place

df.insert( loc=3 , column = 'wood', value =5)
df.head()

,PassengerId,Survived,Pclass,wood,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked,Bilal
0,1,0,3,5,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S,3
1,2,1,1,5,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C,3
2,3,1,3,5,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,5,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S,3
4,5,0,3,5,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S,3

In [17]:
df.insert(loc = 8, column = 'Equipment', value = "football")
df.head(10)

,PassengerId,Survived,Pclass,wood,Name,Sex,Age,SibSp,Equipment,Parch,Ticket,Fare,Cabin,Embarked,Bilal
0,1,0,3,5,"Braund, Mr. Owen Harris",male,22.0,1,football,0,A/5 21171,7.2500,NaN,S,3
1,2,1,1,5,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,football,0,PC 17599,71.2833,C85,C,3
2,3,1,3,5,"Heikkinen, Miss. Laina",female,26.0,0,football,0,STON/O2. 3101282,7.9250,NaN,S,3
3,4,1,1,5,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,football,0,113803,53.1000,C123,S,3
4,5,0,3,5,"Allen, Mr. William Henry",male,35.0,0,football,0,373450,8.0500,NaN,S,3
5,6,0,3,5,"Moran, Mr. James",male,NaN,0,football,0,330877,8.4583,NaN,Q,3
6,7,0,1,5,"McCarthy, Mr. Timothy J",male,54.0,0,football,0,17463,51.8625,E46,S,3
7,8,0,3,5,"Palsson, Master. Gosta Leonard",male,2.0,3,football,1,349909,21.0750,NaN,S,3
8,9,1,3,5,"Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)",female,27.0,0,football,2,347742,11.1333,NaN,S,3
9,10,1,2,5,"Nasser, Mrs. Nicholas (Adele Achem)",female,14.0,1,football,0,237736,30.0708,NaN,C,3

In [18]:
new_row = {
    'Survived' : 1,
    'Sex': 'Male'
    }

print(new_row)

{'Survived': 1, 'Sex': 'Male'}

In [19]:
# Add row or dict in data frame at the end

df = pd.concat([df, pd.DataFrame([new_row])], ignore_index = True)

In [20]:
df.tail()

,PassengerId,Survived,Pclass,wood,Name,Sex,Age,SibSp,Equipment,Parch,Ticket,Fare,Cabin,Embarked,Bilal
887,888.0,1,1.0,5.0,"Graham, Miss. Margaret Edith",female,19.0,0.0,football,0.0,112053,30.00,B42,S,3.0
888,889.0,0,3.0,5.0,"Johnston, Miss. Catherine Helen ""Carrie""",female,NaN,1.0,football,2.0,W./C. 6607,23.45,NaN,S,3.0
889,890.0,1,1.0,5.0,"Behr, Mr. Karl Howell",male,26.0,0.0,football,0.0,111369,30.00,C148,C,3.0
890,891.0,0,3.0,5.0,"Dooley, Mr. Patrick",male,32.0,0.0,football,0.0,370376,7.75,NaN,Q,3.0
891,NaN,1,NaN,NaN,NaN,Male,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN